name: pyrnotebook_class
channels:
  - conda-forge
  - conda 
  - pytorch
  - pypi
dependencies:
  - r-essentials
  - r-base
  - lapack
  - blas
  - r-rmpfr
  - r-tensorflow
  - r-keras
  - r-boot
  - r-caret
  - r-learnr
  - r-rstan
  - r-brms
  - r-mlr
  - r-superlearner
  - r-cairo
  - r-forecast
  - r-autoshiny
  - r-acepack
  - r-rjava
  - r-leaps
  - r-regnet
  - r-aspect
  - r-sem
  - r-polycor
  - r-ggvis
  - r-relimp
  - r-sparklyr
  - r-sparkr
  - r-sparsemvn
  - r-sparsesem
  - r-sparsesvd
  - r-sparsesvm
  - r-volesti
  - r-vocaldia
  - r-vnm
  - r-vmask
  - r-vlmc
  - r-vita
  - r-visualize
  - r-visreg
  - r-visnetwork
  - r-visielse
  - r-visielse
  - r-viridis
  - r-vipor
  - r-viopoints
  - r-violinmplot
  - r-vcov
  - r-vcd
  - r-vbsr
  - r-vbdm
  - r-varsel
  - r-vars
  - r-vared
  - r-var.etp
  - r-utility
  - r-usmap
  - r-usedist
  - r-usaboundaries
  - r-uroot
  - r-urca
  - r-upsvarapprox
  - r-unix
  - r-univrng
  - r-unitizer
  - r-unitedr
  - r-unitcircle
  - r-uniisoregression
  - r-unifed
  - r-unbalhaar
  - r-ump
  - r-ultimixt
  - r-uiucthemes
  - r-ui
  - r-ucminf
  - r-ucbthesis
  - r-twostepclogit
  - r-twosamples
  - r-twitterwidget
  - r-twitter
  - r-twiddler
  - r-tweedie
  - r-tvsmiss
  - r-tvd
  - r-tutorial
  - r-turboem
  - r-tuple
  - r-tunepareto
  - r-tufterhandout
  - r-tufte
  - r-tuckerr.mmgg
  - r-tubern
  - r-tth
  - r-tstutorial
  - r-tstutorial
  - r-tsp
  - r-tsne
  - r-tsmodel
  - r-tseriesmma
  - r-tsdata
  - r-tsc
  - r-tsallisqexp
  - r-trycatchlog
  - r-trustoptim
  - r-trust
  - r-truncreg
  - r-truncnorm
  - r-truncgof
  - r-trueskill
  - r-trotter
  - r-tropicalsparse
  - r-tropalgebra
  - r-tripack
  - r-trimcluster
  - r-triangulation
  - r-triangle
  - r-trendsegmentr
  - r-treeperm
  - r-treelet
  - r-tree
  - r-treeclust
  - r-transport
  - r-transp
  - r-track
  - r-tpauc
  - r-totalcensus
  - r-tosls
  - r-topicmodels
  - r-tokenizers
  - r-tokenbrowser
  - r-todor
  - r-tnet
  - r-tnc
  - r-tmvnsim
  - r-stan
  - r-strucchange
  - r-stringr
  - r-stringi
  - r-stringdist
  - r-stringb
  - r-string2adjmatrix
  - r-stratifiedbalancing
  - r-stopwords
  - r-emplik
  - r-emplik2
  - r-ac3net
  - r-aca
  - r-acceptancesampling
  - r-acd
  - r-acfmperiod
  - r-acopula
  - r-acp
  - r-acs
  - r-acss
  - r-acss.data
  - r-ada
  - r-adagio
  - r-adaptivesparsity
  - r-adaptmcmc
  - r-adaptmt
  - r-adapttest
  - r-ade4
  - r-ade4tkgui
  - r-adegraphics
  - r-adequacymodel
  - r-adgoftest
  - r-adimpro
  - r-admisc
  - r-admit
  - r-admmnet
  - r-adpf
  - r-afc
  - r-agop
  - r-agrmt
  - r-akima
  - r-akmeans
  - r-alabama
  - r-ald
  - r-algdesign
  - r-allan
  - r-allpossiblespellings
  - r-alluvial
  - r-alscpc
  - r-altmeta
  - r-amap
  - r-ambient
  - r-amelia
  - r-aml
  - r-amore
  - r-analyz
  - r-andrews
  - r-anovareplication
  - r-aod
  - r-aods3
  - r-apachelogprocessor
  - r-apfr
  - r-aplpack
  - r-apml0
  - r-apng
  - r-appestimation
  - r-apple
  - r-appliedpredictivemodeling
  - r-approxmatch
  - r-apsrtable
  - r-ar
  - r-arc
  - r-arco
  - r-areaplot
  - r-argondash
  - r-argparse
  - r-argparser
  - r-arht
  - r-aricode
  - r-arm
  - r-armspp
  - r-arpr
  - r-arpobservation
  - r-arrangements
  - r-arrapply
  - r-arrow
  - r-ars
  - r-arsenal
  - r-artiva
  - r-arulescba
  - r-arulesnbminer
  - r-arulessequences
  - r-arxiv
  - r-assertable
  - r-assist
  - r-assortnet
  - r-asyk
  - r-ate
  - r-atlas
  - r-auc
  - r-aucrf
  - r-auto.pca
  - r-autoencoder
  - r-automl
  - r-autopls
  - r-av
  - libgcc
  - gxx_linux-64
  - python
  - pip
  - pandas-profiling
  - plotly
  - jupyterlab-plotly-extension
  - rpy2
  - rsa
  - scikit-image
  - scikit-learn  
  - sklearn-pandas
  - dask
  - pandas-datareader
  - pandas-gbq
  - pandocfilters
  - tensorboard
  - tensorboard-plugin-wit
  - tensorflow
  - tensorflow-datasets
  - tensorflow-estimator
  - tensorflow-hub
  - tensorflow-metadata
  - tensorflow-probability==0.12.2
  - torchtext
  - torchvision
  - tornado
  - Keras
  - Keras-Preprocessing
  - matplotlib
  - matplotlib-venn
  - plotly
  - pycountry
  - scipy
  - scs
  - seaborn
  - statsmodels==0.12.1
  - nbconvert
  - nbformat
  - nest-asyncio
  - networkx
  - nibabel
  - nltk
  - notebook
  - numba
  - numexpr
  - numpy
  - oauth2client
  - oauthlib
  - pytorch
  - arviz==0.11.0
  - mkl-service
  - pymc3
  - pystan
  - sympy
  - r-leaflet
  - r-rgeos
  - r-rgdal
  - r-raster
  - pip:
    - edward