name: pyrnotebook_class
channels:
  - conda-forge
  - conda 
  - pytorch
  - pypi
dependencies:
  - r-essentials
  - r-base
  - lapack
  - blas
  - r-rmpfr
  - notebook
  - numba
  - numexpr
  - numpy
  - oauth2client
  - oauthlib
  - pytorch
  - arviz==0.11.0
  - mkl-service
  - pymc3
  - pystan
  - sympy
  - r-leaflet
  - r-rgeos
  - r-rgdal
  - r-raster
  - pip:
    - edward