install.packages("tidyverse", repos="https://cloud.r-project.org/")
install.packages("rmarkdown", repos="https://cloud.r-project.org/")
install.packages("httr", repos="https://cloud.r-project.org/")
install.packages("shinydashboard", repos="https://cloud.r-project.org/")
install.packages('leaflet', repos="https://cloud.r-project.org/") 
install.packages('ggplot2', repos="https://cloud.r-project.org/")
install.packages("gridExtra", repos="https://cloud.r-project.org/")
install.packages("hexbin", repos="https://cloud.r-project.org/")
install.packages("lubridate", repos="https://cloud.r-project.org/")
install.packages("readr", repos="https://cloud.r-project.org/")
install.packages("dplyr", repos="https://cloud.r-project.org/")
install.packages("magrittr", repos="https://cloud.r-project.org/")
install.packages("tidyr", repos="https://cloud.r-project.org/")
install.packages("knitr", repos="https://cloud.r-project.org/")
install.packages("shiny", repos="https://cloud.r-project.org/")
install.packages("DT", repos="https://cloud.r-project.org/")
install.packages("caTools", repos="https://cloud.r-project.org/")
install.packages("bitops", repos="https://cloud.r-project.org/")
install.packages("rprojroot", repos="https://cloud.r-project.org/")
install.packages("np", repos="https://cloud.r-project.org/")
install.packages("learnr", repos="https://cloud.r-project.org/")
install.packages("DescTools", repos="https://cloud.r-project.org/")
install.packages("here", repos="https://cloud.r-project.org/")
install.packages("ctv", repos="https://cloud.r-project.org/")
install.packages("evtree", repos="https://cloud.r-project.org/")
install.packages("Rcpp", repos="https://cloud.r-project.org/")
install.packages("lavaan", repos="https://cloud.r-project.org/")
install.packages("mokken", repos="https://cloud.r-project.org/")
install.packages("MCMCpack", repos="https://cloud.r-project.org/")
install.packages("lvnet", repos="https://cloud.r-project.org/")
install.packages("semTools", repos="https://cloud.r-project.org/")
install.packages("remotes", repos="https://cloud.r-project.org/")
install.packages("devtools", repos="https://cloud.r-project.org/")
install.packages("randomForestSRC", repos="https://cloud.r-project.org/")
install.packages("wsrf", repos="https://cloud.r-project.org/")
install.packages("ergm", repos="https://cloud.r-project.org/")
install.packages("GeneNet", repos="https://cloud.r-project.org/")
install.packages("sna", repos="https://cloud.r-project.org/")
install.packages("reactable", repos="https://cloud.r-project.org/")
install.packages("mirt", repos="https://cloud.r-project.org/")
install.packages("aspect", repos="https://cloud.r-project.org/")
install.packages("abc", repos="https://cloud.r-project.org/")
install.packages("radiant", repos="https://cloud.r-project.org/")
install.packages("radiant.data", repos="https://cloud.r-project.org/")
install.packages("radiant.design", repos="https://cloud.r-project.org/")
install.packages("radiant.basics", repos="https://cloud.r-project.org/")
install.packages("radiant.model", repos="https://cloud.r-project.org/")
install.packages("radiant.multivariate", repos="https://cloud.r-project.org/")
install.packages("rcc", repos="https://cloud.r-project.org/")
install.packages("RGCCA", repos="https://cloud.r-project.org/")
install.packages("ggquickeda", repos="https://cloud.r-project.org/")
install.packages("openintro", repos="https://cloud.r-project.org/")
install.packages("effects", repos="https://cloud.r-project.org/")
install.packages("StanHeaders", repos="https://cloud.r-project.org/")
install.packages("rstan", repos="https://cloud.r-project.org/")
install.packages("brms", repos="https://cloud.r-project.org/")
install.packages("lavaan", repos="https://cloud.r-project.org/")
install.packages("blavaan", repos="https://cloud.r-project.org/")
install.packages("simsem", repos="https://cloud.r-project.org/")
install.packages("psych", repos="https://cloud.r-project.org/")
install.packages("Ryacas", repos="https://cloud.r-project.org/")
install.packages("metafor", repos="https://cloud.r-project.org/")
install.packages("https://cran.r-project.org/src/contrib/Archive/meta/meta_4.19-2.tar.gz", repos=NULL)
install.packages("https://cran.r-project.org/src/contrib/Archive/netmeta/netmeta_1.5-0.tar.gz", repos=NULL)
devtools::install_github("MathiasHarrer/dmetar")
install.packages("mvmeta", repos="https://cloud.r-project.org/")
install.packages("mvtmeta", repos="https://cloud.r-project.org/")
install.packages("metavcov", repos="https://cloud.r-project.org/")
install.packages("metaviz", repos="https://cloud.r-project.org/")
install.packages("MetaAnalyser", repos="https://cloud.r-project.org/")
install.packages("metaforest", repos="https://cloud.r-project.org/")
devtools::install_github("FedericoComoglio/rSymPy")
devtools::install_github("sachsmc/ggkm")
devtools::install_github("benjaminrich/table1")
devtools::install_github("slowkow/ggrepel")
remotes::install_github("https://github.com/LamaTe/mlr3shiny.git")
install.packages("h2o", type="source", repos=(c("http://h2o-release.s3.amazonaws.com/h2o/latest_stable_R")))
# ctv::install.views("TimeSeries", repos="https://cloud.r-project.org/")
#
library(tensorflow)
install_tensorflow()